services:  
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    env_file:
      - env/env-general.env
      - env/env-calibre.env
    networks:
      - lan
    ports:
      - 2688:2688 # Set to CUSTOM_PORT value
      - 2689:2689 # Set to CUSTOM_HTTPS_PORT value
      - 8081:8081
    volumes:
      - /home/pi/docker/calibre:/config
      - /mnt/usb/downloads:/downloads:z
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:2688"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always