services:  
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    env_file:
      - env/env-general.env
      - env/env-calibre-web.env
    networks:
      - lan
    volumes:
      - /home/pi/docker/calibre-web:/config
      - /mnt/usb/downloads:/downloads:z
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8083"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always