services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    user: "1000:1000"
    env_file:
      - env/env-general.env
      - env/env-filebrowser.env
    networks:
      - lan
    volumes:
      - /home/pi/docker/filebrowser:/config
      - /mnt/usb/downloads/movies:/data/movies:z
      - /mnt/usb/downloads/series:/data/series:z
      - /mnt/usb/downloads/books:/data/books:z
      - /mnt/usb/downloads/audiobooks:/data/audiobooks:z
      - /mnt/usb/downloads:/data/all:z
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always