services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    env_file:
      - env/env-general.env
      - env/env-jellyfin.env
    networks:
      - lan
    volumes:
      - /home/pi/docker/jellyfin/config:/config
      - /home/pi/docker/jellyfin/cache:/cache
      - /mnt/usb/downloads/series:/series:z
      - /mnt/usb/downloads/movies:/movies:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8096/health"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always