services:  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    depends_on:
      - portainer-agent
    env_file:
      - env/env-general.env
    networks:
      - lan
    ports:
      - "9443:9443" # I left this port exposed on purpose if Traefik container fails so I have direct access to container management
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    volumes:
      - /home/pi/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9000/api/system/status"]
      interval: 300s
      timeout: 10s
      retries: 3
    restart: always
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    env_file:
      - env/env-general.env
    networks:
      - lan
    environment:
      AGENT_CLUSTER_ADDR: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:9001/ping"]
      interval: 300s
      timeout: 10s
      retries: 5
    restart: always