services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - env/env-general.env
    networks:
      - lan
    volumes:
      - /home/pi/docker/prowlarr:/config
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9696/ping"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always