services:  
  sftp:
    container_name: sftp
    image: drakkan/sftpgo:latest
    env_file:
      - env/env-general.env
      - env/env-sftp.env
    networks:
      - lan
    ports:
      - "2622:2022" # SFTP
      - "2621:2121" # FTP
      - "60000-60010:60000-60010" # FTP Pasive
      - "10080:10080" # WebDAV
    volumes:
      - /home/pi/docker/sftp:/var/lib/sftpgo
      - /mnt/usb/downloads/movies:/srv/sftpgo/movies:z
      - /mnt/usb/downloads/series:/srv/sftpgo/series:z
      - /mnt/usb/downloads/books:/srv/sftpgo/books:z
      - /mnt/usb/downloads/audiobooks:/srv/sftpgo/audiobooks:z
      - /mnt/usb/downloads:/srv/sftpgo/downloads:z
      - /mnt/usb/backup:/srv/sftpgo/backup
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ['CMD', 'sftpgo', 'ping']
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always