services:  
  samba:
    container_name: samba
    image: dperson/samba:latest
    env_file:
      - env/env-general.env
      - env/env-samba.env
    networks:
      - lan
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /mnt/usb/downloads:/downloads:z
      - /mnt/usb/downloads/movies:/movies:z
      - /mnt/usb/downloads/series:/series:z
      - /mnt/usb/downloads/books:/books:z
      - /mnt/usb/downloads/audiobooks:/audiobooks:z
    command: '-s "Movies;/movies;yes;no;yes;all;pi;pi" -s "Series;/series;yes;no;yes;all;pi;pi" -s "Books;/books;yes;no;yes;all;pi;pi" -s "Audiobooks;/audiobooks;yes;no;yes;all;pi;pi" -s "Downloads;/downloads;yes;no;yes;all;pi;pi" -p'
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    restart: always