services:  
  traefik:
    image: traefik:latest
    container_name: traefik
    env_file:
      - env/env-general.env
    networks:
      - lan
    ports:
      - "80:80"
      - "443:443"
      - "8181:8080"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=false"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/configs/"
      - "--providers.file.watch=true"
      - "--accesslog=false"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8082"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.csr.acme.tlschallenge=true"
      - "--certificatesresolvers.csr.acme.email=me@myemail.com" # Change to your email
      - "--certificatesresolvers.csr.acme.storage=/letsencrypt/acme.json"
      - "--ping"
    volumes:
      - /home/pi/docker/traefik/letsencrypt:/letsencrypt
      - /home/pi/docker/traefik/configs:/configs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging: 
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always