version: "3"
networks:
  lan:
    external: true
include:
  - dc-traefik.yaml
  - dc-portainer.yaml
  - dc-heimdall.yaml
  - dc-portainer.yaml
  - dc-cloudflare-ddns.yaml
  - dc-no-ip2.yaml
  - dc-pihole.yaml
  - dc-minidlna.yaml
  - dc-transmission.yaml
  - dc-nextcloud.yaml
  - dc-samba.yaml
  - dc-ftps.yaml
  - dc-calibre-web.yaml
  - dc-calibre.yaml
  - dc-lazylibrarian.yaml
  - dc-readarr.yaml
  - dc-radarr.yaml
  - dc-sonarr.yaml
  - dc-prowlarr.yaml
  - dc-bazarr.yaml
  - dc-plex.yaml
  - dc-monitoring.yaml
  - dc-jellyfin.yaml
  - dc-filebrowser.yaml
  - dc-sftp.yaml