ip_address: 192.168.20.102 # Change this to your Hue Bridge IP
api_key: "MyApiKey" # Generate this key from Hue Bridge web interface
sensors:
  # With `match_names` set, the exporter will set the names of temperature
  # sensors and light level sensors to that of the motion sensor (the one that
  # you've actually configured in the Hue app)
  match_names: true
  ignore_types:
  - CLIPGenericStatus