global:
  scrape_interval:     15s 
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'traefik'
    scrape_interval: 15s
    static_configs:
      - targets: ['traefik:8082']
  - job_name: 'sftp'
    scrape_interval: 15s
    static_configs:
      - targets: ['sftp:2623']
  - job_name: 'unpoller'
    scrape_interval: 15s
    static_configs:
      - targets: ['unpoller:9130']
  - job_name: 'hue'
    scrape_interval: 90s
    static_configs:
      - targets: ['hue-exporter:9366']
  - job_name: 'netatmo'
    scrape_interval: 90s
    static_configs:
      - targets: ['netatmo-exporter:2112']
  - job_name: 'kuma'
    scrape_interval: 90s
    static_configs:
      - targets: ['kuma:3001']
    basic_auth:
      username: 'MyUserName' # Change this to username you set during first Uptime Kuma start
      password: 'MyStrongPassword' # Change this to password you set during first Uptime Kuma start