http:
  routers:
    cadvisor:
      service: cadvisor
      rule: "Host(`cadvisor.home.local`)"
      tls: {}
      entryPoints:
        - "websecure"
    # Public internet routing with Let's Encrypt certificate, delete this is you do not have or want access from public internet
    cadvisor-public:
      service: cadvisor
      rule: "Host(`cadvisor.my.domain`)"
      tls: 
        certresolver: csr
      entryPoints:
        - "websecure"

  services:
    cadvisor:
      loadBalancer:
        servers:
          - url: "http://cadvisor:8080"
        healthcheck:
          path: "/"
          port: "8080"
          scheme: "http"
          interval: "3s"
          timeout: "100ms"